### ISSUE TITLE
Uninstalling ngshare

### ISSUE THREAD

**Issue by celine168** [lxylxy123456/ngshare#103]
Have you tried uninstalling ngshare, and are there instructions for it? Is it as simple as `helm delete ngshare --purge`?
One thing I noticed was that ngshare is installed under the `kube-system` namespace. I don't know whether makes it difficult to uninstall. Might want to consider adding instructions with deploying `ngshare` on a different namespace like [JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-jupyterhub.html) does, but this is up to you guys.

**Comment by rkevin-arch** [comment]
Yeah, deleting should be that easy (although maybe back up the database first). I'm not sure why it wants to be installed under the `kube-system` namespace, it should install to whatever namespace you specify (and install to the default namespace, not `kube-system`, if one isn't specified). This is intended to be installed under the same namespace as JupyterHub, so the hub can talk to it using `http://ngshare:8080`.

**Comment by celine168** [comment]
I'm not too sure why it didn't install in the default namespace either (it should be the default one if no namespace is specified), but the `ngshare-xxx` pod is under the `kube-system` namespace.

> This is intended to be installed under the same namespace as JupyterHub

I think this is worth adding to the README; by adding a `--namespace` option to `helm install`.

While we are on the similar topic, I think adding the Helm repository is an important step to add to the README as well: 
` helm repo add ngshare https://rkevin-arch.github.io/ngshare-helm-repo/`

**Comment by rkevin-arch** [comment]
The README is sort of out-of-date, I'm working on updating it with more info soon (including how to install https://lxylxy123456/ngshare_exchange rather than using our fork of nbgrader). I'll look into why helm is messing with `kube-system`.

**Comment by celine168** [comment]
Good to know, thank you!
I'm going to open a separate issue about my experience with installing ngshare, if that's ok.

**Comment by rkevin-arch** [comment]
New documentation has been added to [Read the Docs](https://ngshare.readthedocs.io/en/latest/user_guide/uninstall.html), including an uninstallation guide, so I'm going to close this. Let us know if there are issues during uninstallation.
