### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [lxylxy123456/ngshare#112]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by lxylxy123456** [comment]
Hi Tom, 
Do you have a documentation on migrating to GitHub app? I have changed some configurations, but I am not sure whether I am configuring it correctly. 
Also, do I need to change something if I am going to transfer ownership of this repo? 
Eric Li

**Comment by thomasrockhu** [comment]
@lxylxy123456, I see that everything looks good on our side! Thanks for the quick turnaround here.

If you transfer ownership, the new owner may need to re-confirm permissions, but it shouldn't be any more work than adding the integration again.
