### ISSUE TITLE
GET feedback semantics

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#12]
Should [GET /api/feedback/<course_id>/<assignment_id>/<student_id>](https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#get-apifeedbackcourse_idassignment_idstudent_id) return an error when there is no feedback (currently it returns an empty list)

**Comment by Lawrence37** [comment]
I would say no. Keep the empty list.
