### ISSUE TITLE
vserver no such column error (submissions.random)

### ISSUE THREAD

**Issue by Lawrence37** [lxylxy123456/ngshare#15]
The GET /api/submissions/<course_id>/<assignment_id>/<student_id> request fails with sqlalchemy.exc.OperationalError. The reason is "no such column: submissions.random".

**Comment by lxylxy123456** [comment]
Try to stop the server, remove `/tmp/vserver.db`, and then start it. 
I also encountered this problem and am not sure what is the standard way to solve this.

**Comment by Lawrence37** [comment]
Will this be a problem in the production server?

**Comment by lxylxy123456** [comment]
We are not using this in production anyway. So no problem. If you still encounter this problem make sure to notify me. 

Possible reasons of this problem:
1. I am using a hard-coded database (`/tmp/vserver.db`), and hard-coded init program (solution: remove these in production). 
2. sqlite 3 does not allow multiple connections (solution: use a better db). 
3. If you run `pytest`, it will remove `/tmp/vserver.db` to generate initial data again.
