### ISSUE TITLE
Submit assignment permission

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#22]
https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#post-apisubmissioncourse_idassignment_idstudent_id

What does instructor+student mean? Can instructor submit for any student? Or instructor can submit as a student?

**Comment by Lawrence37** [comment]
Students and instructors can submit assignments as themselves.

**Comment by lxylxy123456** [comment]
Completed in 1fc57265665d292fc541234a0825f5269e44f4fd
