### ISSUE TITLE
Drop student_id from assigment submission

### ISSUE THREAD

**Issue by Lawrence37** [lxylxy123456/ngshare#23]
Once proper user authentication is supported, the student ID can be dropped from [`POST /api/submission/<course_id>/<assignment_id>/<student_id>`](https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#post-apisubmissioncourse_idassignment_idstudent_id). The student ID shall be determined from the user's credentials. The request will become `POST /api/submission/<course_id>/<assignment_id>`.

**Comment by lxylxy123456** [comment]
Completed in 3531933f0b7cb3cf358708ffec7bdedec6eacd13

**Comment by lxylxy123456** [comment]
Note that it is not in master branch
