### ISSUE TITLE
SQLite objects can only be used in that same thread

### ISSUE THREAD

**Issue by aalmanza1998** [lxylxy123456/ngshare#29]
I get this error whenever I post an assignment and then try to list it. Any clue what might cause this?

<img width="1274" alt="Screen Shot 2020-03-01 at 11 52 51 AM" src="https://user-images.githubusercontent.com/52981614/75632664-3aae5a80-5bb3-11ea-8513-54d1f9d96bd4.png">

**Comment by lxylxy123456** [comment]
SQLite is not multi-threading, so I guess maybe you are issuing multiple requests at once, so SQLite complains. Can you give me a way to reproduce this issue? Or to fix it, try:
1. Stop server
2. Remove `/tmp/vserver.db` (data will lose)
3. Start server
4. Try again

**Comment by lxylxy123456** [comment]
It seems that there will be a fix. See https://stackoverflow.com/questions/34009296/using-sqlalchemy-session-from-flask-raises-sqlite-objects-created-in-a-thread-c if you want to know more. I am currently fixing it.

**Comment by lxylxy123456** [comment]
@aalmanza1998 I am going to fix it in `master` branch. Are you able to work on `master` branch now? Or do I need to make another copy in `vserver-no-auth` branch?

**Comment by aalmanza1998** [comment]
Just push your changes to master. I restarted vserver and that seemed to fix it too. Thank you for looking into it.

**Comment by lxylxy123456** [comment]
Commit 2ddb599 should be able to fix the issue forever. Please delete branch `vserver-no-auth` once you are done with it.
