### ISSUE TITLE
Listing submissions API

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#3]
https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#request-3

@Lawrence37 Do we need to include all the file lists? (`"notebooks":[...]`)
1. I think the assignment directory tree should be the same as submission directory tree (only files are different)
2. The file list will also be available if the instructor downloads it at `/api/submission/<course_id>/<assignment_id>/<student_id>`. If needed, we can add an option of listing the filenames without downloading them.

**Comment by Lawrence37** [comment]
I believe only the notebook files need to be listed.

The assignment and submission tree should be the same.

We shall see if listing the submitted files is necessary.

**Comment by lxylxy123456** [comment]
So I will leave the API without listing notebook files as for now. 

Also some suggestions on writing the API docs: separate successful situations and unsuccessful:
>Success
>```
>{
>    "success": true,
>    "assignments": [ /* assignment name */, ...]
>}
>```
>Possible fail messages
>* "Course not found"
>* "Assignment not found"

You do not need to guess all possible fail messages at this time. I can do it after I implement it. 

Also, I prefer having examples instead of comments (but feel free to use your the original style):
>```
>{
>    "success": true,
>    "assignments": [ "ass1", "ass2", ... ]
>}
>```
and
>[
>    {
>        "path": "/path/relative/to/root",
>        "content": "base64content=="
>    },
>    ...
>]

**Comment by lxylxy123456** [comment]
@Lawrence37 Note that I am going to close this, though `"notebook"` is still not added in the API. If you need it please reopen or add a new issue.
