### ISSUE TITLE
Remove random string from API

### ISSUE THREAD

**Issue by Lawrence37** [lxylxy123456/ngshare#33]
The random string in nbgrader is used only to prevent students from accessing other students' submissions. The random string only appears in the inbound directory of the exchange. It is not used in the user's cache, so it does not serve as a unique submission identifier, at least for cached submissions. ngshare should be able to prevent unauthorized access by design, so the random string is not needed for ngshare.

This issue is for tracking the removal of random string. @aalmanza1998 and I will revise the API specifications first. @lxylxy123456 will ensure vserver and ngshare follow the new API.

**Comment by lxylxy123456** [comment]
@Lawrence37 I have already removed random strings. vserver should work fine (the tests are also updated). You can consider updating documentation based on my change to [nbgrader.py](https://github.com/lxylxy123456/ngshare/commit/b4574e634af5c7f64a51277024866daa961aed7f#diff-35a5a8f802dbe45e6db686b9b3587d88)

Hint: don't forget to remove "Please supply random str" from possible error messages.
