### ISSUE TITLE
Submission listing notebook list and checksum support

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#36]
API modification: checksum is md5sum, whenever list_only or not return checksum
Database modification: checksum for files
Backend: ...

**Comment by lxylxy123456** [comment]
@Lawrence37 Can you add the rule that get_all=true must have list_only=true?

**Comment by lxylxy123456** [comment]
Also: should API fail or return empty list when using get_latest or timestamp?

**Comment by lxylxy123456** [comment]
Also: it should look more like 
```
{
    "success": true,
    submissions: [
        {
            "timestamp": /* submission timestamp */,
            "files": /* encoded directory tree */
        },
        ...
    ]
}
```

**Comment by Lawrence37** [comment]
I removed get_all and get_latest. If no submission matches the timestamp, the server should respond with "Submission not found."

**Comment by lxylxy123456** [comment]
1. We want to also provide checksum for notebooks (so consider reverting b08a7e27ab0126e77170cb37cab2a9094e154574)
2. What happens to `get_all`?

**Comment by Lawrence37** [comment]
1. I only changed the definitions. The API remains the same. Are you referring to a different commit?
2. It's not necessary because `"timestamp"` can be used to retrieve all submissions.

**Comment by lxylxy123456** [comment]
I see. My brain got short circuit when I was asking 1. I have no more questions now.
