### ISSUE TITLE
Extend API to add students and instructors to a course

### ISSUE THREAD

**Issue by aalmanza1998** [lxylxy123456/ngshare#41]
We need to write documentation and modify ngshare to include support for adding students and instructors to a course

**Comment by lxylxy123456** [comment]
Do you have a clear API docs in mind?

**Comment by aalmanza1998** [comment]
Please see pull request [ #42](https://github.com/lxylxy123456/ngshare/pull/42) for new api documentation

**Comment by lxylxy123456** [comment]
Here is my plan: I am going to support adding a JupyterHub user into the course first (this should be able to be done quickly). 
Then I will begin adding database and allow storing user information (e.g. first name, email). I may need to discuss with Kevin about how to design the database to make it efficient.

**Comment by lxylxy123456** [comment]
I changed the return format a little bit in 34a249f so that the backend do not need to write duplicated code.

**Comment by lxylxy123456** [comment]
Issues from #42 :
- [ ] What happens if adding an existing student as instructor (and vice versa?)
- [ ] Should we store user info (first name etc) for each course in another database?
We are going to merge #42 at this point.
