### ISSUE TITLE
Testing setup documentation

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#48]
I wrote some setup docs a long time ago: https://github.com/lxylxy123456/ngshare#installation-and-setup
I just saw @rkevin-arch also wrote the documentation in https://github.com/lxylxy123456/ngshare/tree/master/testing#testing-setup
Maybe we should merge them?

**Comment by rkevin-arch** [comment]
Tentatively closed, but might update when I finish kubespawner powered JH managed services properly.

**Comment by lxylxy123456** [comment]
@rkevin-arch You can add another issue for this
