### ISSUE TITLE
Using None instead of empty string

### ISSUE THREAD

**Issue by aalmanza1998** [lxylxy123456/ngshare#50]
I was wondering whether it would be better to use `None` instead of empty strings for the optional fields in ngshare. Currently nbgrader allows for the first name, last name and email of a student to be `None`. 
<img width="1115" alt="Screen Shot 2020-03-28 at 8 35 02 PM" src="https://user-images.githubusercontent.com/52981614/77839682-a98bbe80-7133-11ea-93ab-73e342eca11a.png">
but ngshare only allows for empty strings, not for None.
<img width="1160" alt="Screen Shot 2020-03-28 at 8 37 10 PM" src="https://user-images.githubusercontent.com/52981614/77839706-ee175a00-7133-11ea-9bf8-0c54344c26c7.png">
<img width="475" alt="Screen Shot 2020-03-28 at 8 38 18 PM" src="https://user-images.githubusercontent.com/52981614/77839725-1acb7180-7134-11ea-939b-66d6d18c9557.png">

Not a big deal but wanted to see your thoughts.

**Comment by lxylxy123456** [comment]
HTTP GET is only receiving strings, so for None you have to not pass "last_name=". I think empty string is good enough. The instructor can also just put "last_name=N/A". 

Sorry, I lost my emails for a few days, so did not see this comment.
