### ISSUE TITLE
Timestamp timezone

### ISSUE THREAD

**Issue by Lawrence37** [lxylxy123456/ngshare#53]
When ngshare creates a datetime object, the timezone information is missing. This causes the timestamp string to have no timezone (for example, "2020-01-30 10:30:47.524219 " instead of "2020-01-30 10:30:47.524219 UTC").
https://github.com/lxylxy123456/ngshare/blob/d3438c7bb486cf3a2794020379ad24db547a281c/ngshare/database/database.py#L171
Maybe we can use this instead.
```python
        self.timestamp = datetime.datetime.now(datetime.timezone.utc)
```

**Comment by lxylxy123456** [comment]
So to be honest, the backend does not care about whether there are timezoon info. The change you propose does not break test cases in backend, so feel free to merge the change in #54 at any time.
