### ISSUE TITLE
api-specifications.md Error Codes

### ISSUE THREAD

**Issue by Miniland1333** [lxylxy123456/ngshare#57]
Hello Team KALE,
          For your api-specifications documentation, would you be able to add to your documentation the HTTP status codes that your various responses generate? Having these status codes properly implemented and documented would allow for better error handling.

Example: 
------------
Status Code |  Status Message
-----|--------------
200 | Okay
401 | Login required
403 | Permission denied
404 | Course not found
404 | Instructor not found

Thanks,
-Henry Agnew
LibreTexts Lead Full-Stack Developer
UC Davis, class of 2020

**Comment by rkevin-arch** [comment]
Correct me if I'm wrong, but I think ngshare always returns 200, and failure is indicated using `"success": "false"` in the result JSON. @lxylxy123456 might be better suited to answer this question. I agree that using the right HTTP status codes might be a good idea, and we'll probably look into that in the future.

**Comment by Miniland1333** [comment]
Thanks for looking into this issue! HTTP status codes are an essential standard that all REST APIs should follow, and it would be advisable to adopt this standard before production.

I do have other topics I would like to discuss with you all, but I will wait until after the meeting in case you have already addressed them.

**Comment by Miniland1333** [comment]
Relating to fe6769e,

Please do not use HTTP 301 redirects for "not authenticated" as they are both **permanent** and not meant for this purpose. For a client not being authenticated, you should instead use `401 Unauthorized`. One of the only relevant uses to you of `301 Permanent Redirect` would be if you had changed the name of one of your APIs, but this uncommon.

Errors caused due to the client's request should be of the 4xx series and errors caused due to server malfunction should be 5xx series. The ones I listed in my example are a good start, but let me know if you need assistance with selecting the correct status codes for your other error types. Returning the general 400 or 500 codes should only be done when none of the other more specific 4xx or 5xx series codes are applicable.

These error codes will be really useful when others outside of your development team want to start using your API!
-Henry

**Comment by lxylxy123456** [comment]
@Miniland1333 Thank you for the advices. For things like "Course not found" errors I will discuss with other group memebers, and I think we would be able to fix them soon. (Though I am not sure how to decide the code for each exact situation, like “400 incorrect time format”?)

For authentication, the response code is actually 302 (I remembered it incorrectly). This is by default used in [`HubAuthenticated`](https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html#jupyterhub.services.auth.HubAuthenticated), and I would need to do some research on how to change this behavior.

**Comment by Miniland1333** [comment]
Since incorrect time format isn't doesn't fit `401 Unauthorized`,`403 Forbidden`, `404 Not Found`, `409 Conflict` nor `5xx Server Error`, it would be a case where `400 Bad Request` is acceptable as you proposed.

`302 Temporary Redirect` is certainly better than a `301 Permanent Redirect`. `401` is standard for REST APIs, but it looks like in the HubAuthenticated that they may be doing something custom that you don't want to overwrite. My advice is going off of standard REST API standards, so in cases where they are doing custom behavior like this my advice may not be applicable.
If they are already using 302 for unauthenticated, I would recommend sticking with it.

For your remaining errors, you should have the freedom in order to conform with the standard HTTP status codes.

**Comment by lxylxy123456** [comment]
@Miniland1333 Thanks for confirmation. I have already implemented the changes in #60 (with update to documentations). I need to wait for @aalmanza1998 and @Lawrence37 to change the front-end code before merging it. 

For changing 302 to 401, it is possible (in #61), but I do not recommend this work around (probably won't merge this)

**Comment by Miniland1333** [comment]
That sounds good with merging #60 and not merging #61! Definitely test any changes you make in case there is any additional behavior with how Jupyter uses the API that is different than how normal REST responses are handled.

Could you please describe what `Cannot remove last instructor` is used for? Depending on your application, there is a chance it is better as a `403`,`500`, or even `400`. Other than this the rest of your assignments in api-specifications.md made immediate sense to me.

Thanks again for working on this.

**Comment by lxylxy123456** [comment]
`Cannot remove last instructor` is used when a course instructor want to remove him/her self from the course, but he/she is the only instructor in the course. At that time the course cannot be managed by anyone (an undesirable state). 

I think it is not 500. But I am not sure whether it should be 400, 403, or 409.

**Comment by Miniland1333** [comment]
> 409 Conflict - The request could not be completed due to a conflict with the current state of the resource. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request.

Based on the definition and your description, `409` or `400` seem to be equally acceptable options. This is a grey area, so you can do whichever one you prefer or see what other APIs do in similar circumstances (cannot delete self).
