### ISSUE TITLE
List all submissions for an assignment from a particular student API change

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#6]
For redundancy we may want to add "student_id" here:

https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#response-4

**Comment by Lawrence37** [comment]
What is/are the benefits and can we make it optional to implement?

**Comment by lxylxy123456** [comment]
If you call the wrong API (/api/submissions/<course_id>/<assignment_id>) you will catch it by placing an assert on checking student_id. Also it makes the two APIs look the same (which may probably save some code in the backend)

**Comment by Lawrence37** [comment]
You can also assert that student_id doesn't exist. I will add it as an optional field.

**Comment by lxylxy123456** [comment]
I think asserting student_id does not exist does not make sense. You should either make it a required field (it is just one line change in backend), or we can wait for other group members to discuss.

**Comment by Lawrence37** [comment]
We are talking about testing the server/client. I see no point in forcing implementations to have the student_id simply for testing purposes. I suppose it can be useful for hiding other student's submissions in case of a terrible coding mistake, but I think that should not be a responsibility of the API.

**Comment by lxylxy123456** [comment]
What do you mean by testing? 

I believe the API should make it clear about what will be returned. If you want to have this checking feature, you need to either:
1. Say in API that `student_id` will be returned, client will check value of student_id
2. Say in API that `student_id` must not be returned, and client will assert student_id doesn't exist
Or if you say in API it is an optional value (server decides whether to return it), then the client cannot check anything.

**Comment by Lawrence37** [comment]
By testing, I mean making sure the client code issues the correct request and the server code sends the correct submissions.

If the field is optional, the client can still do a two part check by seeing if the field exists, and if it does, check the value.

**Comment by lxylxy123456** [comment]
I see. You can make it optional in API and I will make vserver return the student_id value. We can ask Abigail and Kevin about this change on Wednesday.
