### ISSUE TITLE
Course creating contorl

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#65]
Make sure that administration can control who can create courses

**Comment by rkevin-arch** [comment]
Superuser: can create courses, delete courses, modify instructors for a course
Instructors: cannot create new courses, cannot delete courses they teach, cannot add / modify co-instructors for the course, can do everything else
Students: no change

**Comment by lxylxy123456** [comment]
Here is my idea:
* Only super users can create courses / delete courses
* Everything else is the same
@rkevin-arch How do you think super users should

**Comment by lxylxy123456** [comment]
I will implement Kevin's. The only problem is that instructors cannot add TA by them selves.

**Comment by lxylxy123456** [comment]
I will going to use command line arguments with ',' splitted values.

**Comment by lxylxy123456** [comment]
@rkevin-arch should we allow instructors to update their email addresses?
