### ISSUE TITLE
Download a student's submitted assignment API semantics

### ISSUE THREAD

**Issue by lxylxy123456** [lxylxy123456/ngshare#7]
https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#get-apisubmissioncourse_idassignment_idstudent_id

Is the download going to download the latest submission? Can a instructor download an earlier version?

**Comment by aalmanza1998** [comment]
I think it should be the latest one. In exchange collect a student's submission is replaced by the newest one if they submit more than once. Older assignments submissions are kept in the inbound directory.

**Comment by aalmanza1998** [comment]
How can we specify what version of the assignment to fetch? I know they are distinguished by timestamp and a random str.

**Comment by lxylxy123456** [comment]
We can use an optional HTTP GET parameter. When not specified, download the latest. @Lawrence37 can you update the API docs?

**Comment by aalmanza1998** [comment]
yes but what should this parameter be?

**Comment by lxylxy123456** [comment]
Is the timestamp and random str separately stored? or stored together? 
I think we should basically specify both of them.

**Comment by aalmanza1998** [comment]
they are separate. Here's an example of a submission name for reference
`aalmanza+assignment2+2020-02-22 20:19:51.198213 UTC+x3KiPbesMV3m`

**Comment by lxylxy123456** [comment]
But aren't they still stored in the same string? What does `+` mean here?

**Comment by aalmanza1998** [comment]
oh yes they are store in the same `assignment_filename` string. The + is part of the submission name. I think maybe we can just use the random str, maybe call that submission id? Not sure how random they are and if there would ever be a conflict between two assignments.

**Comment by aalmanza1998** [comment]
`            self.assignment_filename = '{}+{}+{}+{}'.format(
                student_id, self.coursedir.assignment_id, self.timestamp, random_str)`

**Comment by aalmanza1998** [comment]
or would you want to include the whole name of the submission as an HTTP parameter?

**Comment by lxylxy123456** [comment]
I believe it is for preventing collision, so we should use both random and timestamp. Maybe there need to be a small change on the database structure.

**Comment by aalmanza1998** [comment]
do we need to add the random str in the response of `GET /api/submissions/<course_id>/<assignment_id>` and `GET /api/submissions/<course_id>/<assignment_id>/<student_id>`

**Comment by lxylxy123456** [comment]
Yes, we should. You can add a separate issue and assign it to me.
