### ISSUE TITLE
Taking this to the next level

### ISSUE THREAD

**Issue by willingc** [lxylxy123456/ngshare#72]
Great work so far. You have a cool project here.

I would recommend trying a few things to improve code maintainability down the road:
- set up a CI system for testing (CircleCI, Azure Pipelines, whatever)
- set up a code coverage tool for automated reporting
- add some documentation deployed on ReadTheDocs 
- add badges for the above into the top of the main README
- consider adding the black project for python code consistency

Well done. cc/ @moorepants

**Comment by lxylxy123456** [comment]
I have been working on these, and here are the results so far (need to wait for everything to merge into master before some badges can display correctly)
* I am using Travis CI (same as nbgrader)
* Badges are added: https://github.com/lxylxy123456/ngshare/tree/sudo-black-travis-docs#ngshare
* Coding style will be black (very convenient to use)
* Code coverage > 98%: https://codecov.io/gh/lxylxy123456/ngshare/commit/3346f6782fab553141d2df7c47ce8709930a7360
* Some documents are up: https://ngshare.readthedocs.io/en/sudo-black-travis-docs/

**Comment by moorepants** [comment]
Nice work on all this!

**Comment by willingc** [comment]
Way to go @lxylxy123456! I made some suggestions on the open PRs not as a criticism but as a way for you to learn :cake:

**Comment by willingc** [comment]
@lxylxy123456 I think you have completed all of the above suggestions so I am going to close this.
