### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by celine168** [lxylxy123456/ngshare#97]
Hello,
We are trying to install ngshare, but `helm install ngshare helmchart/ngshare` returns an error that helm install can only accept one argument.

Also, after changing the directory to helmchart and running `helm install ngshare` we get this error:
```
Error: parse error in "ngshare/templates/_helpers.tpl": template: ngshare/templates/_helpers.tpl:58: function "get" not defined
```

**Comment by celine168** [comment]
I noticed that there was a helm repository before, but it seems to be down. Is it intended to be up?
Thank you in advance.

**Comment by rkevin-arch** [comment]
That repo is up, but you have to specify a --version. The latest build is `0.0.1-n224.hc591154`, I believe. I'm not sure what the issue with the helm chart is, but I'm using helm v3.2.0, maybe that's the issue? I haven't tested if the helm chart works with helm2.

**Comment by celine168** [comment]
I see, that is most likely the problem. How possible is it to also make the Chart available on helm2? There seems to be risk on our end for converting from helm2 to helm3, especially [JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm3.html), which isn't yet officially supported.

**Comment by rkevin-arch** [comment]
Fair enough, I'll add helm2 support soon. I believe there's already some support for Z2JH on helm3 (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1543) and during testing I haven't encountered any problems, but I do agree that supporting helm2 is a good idea. I'll look into it.
