### ISSUE TITLE
Polish the documentation

### ISSUE THREAD

**Issue by Lawrence37** [lxylxy123456/ngshare#98]
While reviewing the documentation, I made some changes which you will see in a pull request. There are some additional things that we may want to address.

- [x] Building the HTML documentation results in this warning: `html_static_path entry '_static' does not exist.`
- [x] Add all dependency installation instructions for rendering the tikz figure in the documentation. I get `LaTeX error: "File 'standalone.cls' not found."`
- [x] Consistent capitalization for section titles. Ex: "Extra features" vs. "Extra Features"
- [x] Prominently display a link to this repository in the contributor guide.
- [x] Add developer installation instructions to the contributor guide.
- [x] Debate placement of the "Install vngshare" section. I think it should go under the contributor guide.
- [x] Consider removing the top level of the APIs hierarchy. In other words, make "API Definitions", "Authentication", etc. direct children of "APIS" rather than under "APIS" -> "APIs".
- [x] Discuss whether or not "Removing" should be in the API definitions.
- [x] Consider adding some formatting to "HTTP ### &lt;reason&gt;" texts in the "Request and Response Format" section.
- [x] Talk about the 500 status code in the user documentation. Currently, it is only in the "Request and Response Format" section and it says to submit a bug report. A user may not see this message if it's not in the user documentation.
- [x] Reword "Submissions of the instructor are not removed" in the course APIs section. It is not 100% clear what the sentence is saying.
- [x] Debate the inclusion of the "Development History" section. It doesn't seem relevant to users and future developers.
- [x] Add our justifications for using certain technologies in the "Decisions" section.
- [x] Add more details to the "Development" section. For example, explain what the code does.
- [ ] ~~Add introduction in the user documentation explaining what nghsare is.~~ I missed the home page. I will review that.
- [x] Explain that a plugin is needed for ngshare to work with nbgrader. This will probably be resolved when the "Install nghsare" section has been written, but I'm putting this here as a reminder.
- [x] Explain what "JupyterHub authentication" is in the "Authentication" page.

**Comment by rkevin-arch** [comment]
We resolved this via Zoom but still putting it here for documentation purposes: rendering the tikz image needs some dependencies. On Arch Linux, this can be installed using `pacman -S texlive-core texlive-latexextra texlive-pictures`. Other distros may have slightly different package names. TODO: add documentation on how to build docs

**Comment by lxylxy123456** [comment]
@rkevin-arch You can put this in the documentation. I guess Fedora is basically the same.

**Comment by lxylxy123456** [comment]
No, they are not the same. You can just put the note you wrote ("other distros may ...") on docs

**Comment by lxylxy123456** [comment]
@rkevin-arch You can add a link to: https://github.com/sphinx-contrib/tikz#prerequisites-and-configuration

**Comment by lxylxy123456** [comment]
Or this: https://sphinxcontrib-tikz.readthedocs.io/en/latest/#prerequisites-and-configuration

**Comment by rkevin-arch** [comment]
Closing since we're mostly finished with documentation updates
